# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Main-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: doge_finances

    steps:
      - uses: actions/checkout@v2      
      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        uses: subosito/flutter-action@v1.5.3
        # with:
          # The Flutter version to make available on the path
          # flutter-version: # optional
          # The Flutter build release channel
          # channel: # optional, default is stable
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
